require_relative "../app/models/student.rb"

s1 = Student.create(name: "Takeshi", location: "London", age:20, contact_email: "1@gmail.com")
s2 = Student.create(name: "Dave", location: "Manchester", age:30, contact_email: "2@gmail.com")
s3 = Student.create(name: "Dan", location: "Leeds", age:40, contact_email: "3@gmail.com")
s4 = Student.create(name: "Tom", location: "London", age:50, contact_email: "4@gmail.com")
s5 = Student.create(name: "Tony", location: "Dublin", age:60, contact_email: "5@gmail.com")
s6 = Student.create(name: "Naomi", location: "London", age:34, contact_email: "6@gmail.com")
s7 = Student.create(name: "Henry", location: "Liverpool", age:40, contact_email: "7@gmail.com")
s8 = Student.create(name: "Aya", location: "Oxford", age:15, contact_email: "8@gmail.com")

t1 = Tutor.create(name: "David", location: "London", language: "PHP", experience: 5, price: 100, contact_email: "9@gmail.com")
t2 = Tutor.create(name: "David", location: "London", language: "JavaScript", experience: 5, price: 100, contact_email: "9@gmail.com")
t3 = Tutor.create(name: "David", location: "London", language: "Ruby", experience: 5, price: 100, contact_email: "9@gmail.com")
t4 = Tutor.create(name: "Yan", location: "Leeds", language: "Ruby", experience: 5, price: 200, contact_email: "10@gmail.com")
t5 = Tutor.create(name: "Jess", location: "Manchester", language: "C#", experience: 3, price: 70, contact_email: "11@gmail.com")
t6 = Tutor.create(name: "Teru", location: "Tokyo", language: "Python", experience: 3, price: 65, contact_email: "12@gmail.com")
t7 = Tutor.create(name: "Ryan", location: "Dublin", language: "C++", experience: 2, price: 50, contact_email: "13@gmail.com")
t8 = Tutor.create(name: "Daniel", location: "Liverpool", language: "PHP", experience: 3, price: 55, contact_email: "14@gmail.com")
t9 = Tutor.create(name: "Erisa", location: "Swansea", language: "JavaScript", experience: 4, price: 120, contact_email: "15@gmail.com")
t10 = Tutor.create(name: "Erisa", location: "Swansea", language: "Ruby", experience: 5, price: 150, contact_email: "15@gmail.com")

r1 = Review.create(student_id: s1.id, student_own_level: 3, tutor_id: t4.id, rating_for_tutor: 5, comment: "good in general")
r2 = Review.create(student_id: s2.id, student_own_level: 3, tutor_id: t5.id, rating_for_tutor: 1, comment: "aaaa")
r3 = Review.create(student_id: s3.id, student_own_level: 3, tutor_id: t4.id, rating_for_tutor: 2, comment: "feZC in general")
r4 = Review.create(student_id: s4.id, student_own_level: 5, tutor_id: t6.id, rating_for_tutor: 3, comment: "jkood iffsneral")
r5 = Review.create(student_id: s4.id, student_own_level: 4, tutor_id: t7.id, rating_for_tutor: 3, comment: "ehhhhod in general")
r6 = Review.create(student_id: s5.id, student_own_level: 2, tutor_id: t8.id, rating_for_tutor: 4, comment: "qqod in gefral")
r7 = Review.create(student_id: s6.id, student_own_level: 2, tutor_id: t3.id, rating_for_tutor: 3, comment: "oocsbiaveral")
r8 = Review.create(student_id: s2.id, student_own_level: 2, tutor_id: t3.id, rating_for_tutor: 5, comment: "goZCaboal")
r9 = Review.create(student_id: s7.id, student_own_level: 1, tutor_id: t2.id, rating_for_tutor: 1, comment: "sfCSkncal")
r10 = Review.create(student_id: s7.id, student_own_level: 1, tutor_id: t1.id, rating_for_tutor: 1, comment: "fCin general")
r11 = Review.create(student_id: s7.id, student_own_level: 1, tutor_id: t1.id, rating_for_tutor: 1, comment: "gxbls; zcnl")